books_keyboard = 'books_keyboard'
book_keyboard = 'book_keyboard'
confirm_keyboard = 'confirm_keyboard'
order_keyboard = 'order_keyboard'
orders_keyboard = 'orders_keyboard'
basket_keyboard = 'basket_keyboard'
yes_no_keyboard = 'yes_no_keyboard'
delivery_keyboard = 'delivery_keyboard'
paginate_keyboard = 'paginate_keyboard'
geo_keyboard = 'geo_keyboard'
langs_keyboard = 'langs_keyboard'
regions_keyboard = 'regions_keyboard'
districts_keyboard = 'districts_keyboard'
back_next_keyboard = 'back_next_keyboard'
dates_keyboard = 'dates_keyboard'
times_keyboard = 'times_keyboard'

