main_menu_keyboard = 'main_menu_keyboard'
passenger_parcel_keyboard = 'passenger_parcel_keyboard'
settings_keyboard = 'settings_keyboard'
phone_number_keyboard = 'phone_number_keyboard'
location_keyboard = 'location_keyboard'
driver_keyboard = 'driver_keyboard'
active_driver_keyboard = 'active_driver_keyboard'
